# Generated by Django 5.2.3 on 2025-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CASUAL', 'Casual Party'), ('BIRTHDAY', 'Birthday Party'), ('WEDDING', 'Wedding Party'), ('FORMAL', 'Formal Party')], default='CASUAL', max_length=15),
        ),
    ]
