# Generated by Django 5.2.3 on 2025-08-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images/favicon.png', upload_to='event_images/'),
        ),
    ]
